### ISSUE TITLE
Disable Sidebar sliding out

### ISSUE THREAD

**Issue by modernminimalist** [EliWimmer/notion-style-tweaks#4]
Can you please add tweak to disable hidden sidebar from sliding out whenever mouse is near left side of screen? Thank you

**Comment by EliWimmer** [comment]
Done! Will be in next release (v0.4.0) 👍

**Comment by modernminimalist** [comment]
Awesome! Thank you

**Comment by EliWimmer** [comment]
Released!

**Comment by modernminimalist** [comment]
Thank you so much! That is so helpful. Just bought you coffee on buymeacoffee

**Comment by modernminimalist** [comment]
Where do I submit other tweak suggestions with pics and attempted code?

I am trying to get grouped database view with slim margins but having trouble getting code to consistently apply it to all grouped database views.
![image](https://user-images.githubusercontent.com/74276888/154368765-2cdcdd17-c26b-4c54-acc9-42c594e88d3a.png)
