### ISSUE TITLE
A `New` button on database displays a wrong color out of the theme.

### ISSUE THREAD

**Issue by wmCmo** [EliWimmer/notion-style-tweaks#9]
When I *hold* the mouse click on the arrow of `New` button on database, in displays an original blue color of Notion out of the theme I'm using (it was **Nord**)
![image](https://user-images.githubusercontent.com/51499433/154805950-d5d5b169-fd16-4b7e-814b-7b48fb2b35bf.png)

**Comment by EliWimmer** [comment]
Fixed in v.0.5.2 - Released

Thanks for reporting!
